version: "3.9"

services:
  app:
    image: php:8.2-fpm
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    depends_on:
      - db
    command: >
      sh -c "
      php-fpm
      "

  db:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: role_based_admin
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
