version: "3.9"

services:
  app:
    image: php:8.2-fpm
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    depends_on:
      - db
    command: >
      sh -c "
      apt-get update &&
      apt-get install -y git unzip libzip-dev &&
      docker-php-ext-install pdo pdo_mysql zip &&
      php artisan key:generate &&
      php artisan migrate --force &&
      php artisan db:seed &&
      php artisan serve --host=0.0.0.0 --port=8000
      "
    ports:
      - "8000:8000"

  db:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: role_based_admin
    ports:
      - "3306:3306"
